from __future__ import annotations

from agent.providers.base import ProviderRequest, ProviderResult


class NoopProvider:
    """Deterministic provider used to test the app-builder contract without API keys."""

    name = "noop"

    def generate(self, request: ProviderRequest) -> ProviderResult:
        task_slug = "-".join(part for part in request.task.lower().split() if part) or "task"
        content = (
            "# Kodex Generated Plan\n\n"
            f"Task: {request.task}\n\n"
            "This file was generated by the noop provider. It proves the app-builder "
            "pipeline can compile specs, build context, request generation, and return "
            "safe file candidates without touching the repository.\n"
        )
        return ProviderResult(
            ok=True,
            message="noop provider generated a deterministic planning artifact",
            files={f"generated/{task_slug}.md": content},
            diagnostics=[],
            raw=None,
        )
